### ISSUE TITLE
PCT Oregon resupplies

### ISSUE THREAD

**Issue by rlinehan** [nfagerlund/camping_food#4]
1. Start: Etna (mile 1600,  55 miles, **5 days** - 11 miles/day)
    - Breakfast: 4
    - Lunch: 5
    - Dinner: 5
2. Seiad Valley (mile 1655, 63 miles, **5 days** - 12.6 miles/day)
    - Breakfast: 5
    - Lunch: 5
    - Dinner: 4 (1 at Callahan's)
3. Callahan's (mile 1718, 55 miles, **4 days** - 13.75 miles/day)
    - Possible stop at Hyatt Lake Resort? (mile 1744)
    - Breakfast: 3 (1 at Callahan's)
    - Lunch: 4
    - Dinner: 3 (1 at Fish Lake)
5. Fish Lake (mile 1773, 48 miles, **4 days** - 12 miles/day)
    - **UPS**
    - Breakfast: 3 (1 at Fish Lake)
    - Lunch: 4
    - Dinner: 3 (1 at Mazama Village)
7. Mazama Village (mile 1821, 85 miles BUT also Rim alternate which is 4.5 miles shorter so 80, **6 days** - 13.33 miles/day) 
    - Breakfast: 6
    - Lunch: 6
    - Dinner: 6
9. Shelter Cove (mile 1906, 89 miles, **6 days** - 14.833 miles/day)
    - Possible stop at Elk Lake Resort? (mile 1952)
    - **UPS**
    - Breakfast: 6
    - Lunch: 6
    - Dinner: 5 (1 at BLYC)
10. Big Lake Youth Camp (mile 1995, 102 miles, **6 days** - 17 miles/day)
    - Probable stop at Olallie Lake (mile 2046) - fuel, beer, snacks
    - Breakfast: 5 (1 at BLYC) (but maybe do 6 to have 1 morning of Timberline?)
    - Lunch: 6
    - Dinner: 6
11. Timberline (mile 2097, 50 miles, **4 days**)
    - Breakfast: 3 (1 at Timberline)
    - Lunch: 4
    - Dinner: 3
- End: Cascade Locks, mile 2147

**Comment by nfagerlund** [comment]
Cherries bag of trail mix = 240g, Nick eats a bit less than that per day and Ruth less still. (~170) call it 400g a day for the both of us. 

gallon ziplock of it is 2100g, quart is 600g. We have 11,100g mixed.

**Comment by rlinehan** [comment]
We did not eat this much trail mix.
