### ISSUE TITLE
Olympics 2024

### ISSUE THREAD

**Issue by rlinehan** [nfagerlund/camping_food#7]
# 5 Breakfasts
- [x] rice pudding
- [x] chocolate cherry oatmeal
- [x] blueberry oatmeal
- [x] grits
    - [x] condiments
- [x] mashed potatoes
    - [x] condiments

# 5 Lunches
- [x] sojourner noodles
- [x] sojourner noodles
- [x] moroccan couscous
     - [x] condiments
- [x] cowboy caviar couscous
    - [x] condiments
- [x] Skurka beans
    - [x] condiments

# 5 Dinners
- [x] tart red lentils
    - [x] condiments
- [x] moth beans
    - [x] condiments
- [x] collards
    - [x] condiments
- [x] spaghetti
    - [x] condiments
- [x] cottage pie

# Snacks
- [x] 20 PB cups (2 per day each)
- [x] 5 olive packets
- [x] 10 cliff bars (1 per day each)
- [x] trail mix
- [x] everything bagel nuts
- [x] cheese crisps
- [x] pepper cheese seed crackers
- [x] haribo
- [x] 3 energy chews + 2 spring energy
- [x] mango
- [x] gummies
- [x] salt candy
- [x] trail butter

# Drinks etc.
- [x] 5 TJs coffee
- [x] 5 Mount Hagen coffee
- [x] 4 cider (2 nights)
- [x] 4 spicy hot chocolate (2 night)
- [x] 2 misc hot chocolate (1 nights)
- [x] 2 miso soup
- [x] 4-5 energy drinks
- [x] nido

# Misc
- [x] 14 salt pills
- [x] 2 ziplocks for trash

**Comment by rlinehan** [comment]
To dehydrate:
- [x] corn (sojourner noodles, cowboy caviar)
- [x] cilantro (sojourner noodles)
- [x] onions (spaghetti, grits, cottage pie)
- [x] black beans (cowboy caviar)
- [x] chickpeas (moroccan couscous)
- [x] mixed veggies (cottage pie)
- [x] ground beef (spaghetti, cottage pie)
- [x] celery (cottage pie)
- [x] tomato paste (cottage pie)
- [x] collards + brown rice

To buy:
- [x] ramen (4 packets)
- [x] fritos - 1 snack bag
- [x] celery

**Comment by nfagerlund** [comment]
Hey, I’m marking meals done once they’re assembled *and* all their condiments are added to the cherry bag in the staging bin.

**Comment by nfagerlund** [comment]
Note to self, update the rice pudding with home dried rice

**Comment by nfagerlund** [comment]
We’re out of sriracha and soy sauce packets

**Comment by nfagerlund** [comment]
THIS time around, we are taking 1360g (two quart bags) of trail mix for 5 days hiking, based on Ruth’s comment that I should try 2/3 the estimate from the PCT planning (which had resulted in way too much trail mix). 400g * 5 * 2/3 = 1333.33g

**Comment by nfagerlund** [comment]
(But I didn’t want to repack the bags to remove the extra 30g lol)

**Comment by nfagerlund** [comment]
Ghee packets are 1.5 T if you’re making your own.

**Comment by nfagerlund** [comment]
Also, the narrower bag roll is best for packets, it divides neatly into 3.

**Comment by nfagerlund** [comment]
Ghee hardens fast in the freezer. Sesame oil takes ages but becomes a stiff slush, have faith. Soy sauce is hopeless.

**Comment by nfagerlund** [comment]
We ate all but 230g of trail mix, so, decent estimate.

**Comment by nfagerlund** [comment]
hell yeah
